### ISSUE TITLE
Amir

### ISSUE THREAD

**Issue by Maximilian313** [darksilentcore/braye-rofagha-dar-zoomit#1]
این دراز گوشی که «عر عر» می‌کند را حتی با فحاشی، حلال کنید...
دوستی جز شما نداشتم...

**Comment by darksilentcore** [comment]
سلطان
تو مرا به کام مرگ هم بکشانی
کامی شیرین است

**Comment by Maximilian313** [comment]
سپاس از اینکه مرا حلال کرده‌اید=))))))))))))))
چگونه در سرور دیسکورد شما بِپِیوَندَم؟
یکساعتیست که سعی بر ایجاد حساب کاربری در دیسکورد به کمک tor browser  دارم؛ اما سرویس کپچا...

**Comment by darksilentcore** [comment]
راستی اگر میشه یه لینک تو زومیت بزار که بقیه هم بخونن
برای من که پرید

**Comment by darksilentcore** [comment]
دیسکورد فیلتر نیست

**Comment by darksilentcore** [comment]
لینک
hey join me on Discord! Invite expires in 7 days. https://discord.gg/92UnUU4q

**Comment by Maximilian313** [comment]
چشم سریعاً لینک سرور دیسکورد را برای عزیزان و بزرگواران ارسال خواهم کرد.

**Comment by darksilentcore** [comment]
فداتو
هم ایده از تو بود
هم بنیانگذار تو هستی
ولی وجدانن دیسکورد عجب چیزیه
به زبان جاوااسکریپت نوشته شده
زیبا خوش تراش ساده حرفه ای

**Comment by Maximilian313** [comment]
[ماکسیمیلیان](https://www.zoomit.ir/user/mazdarimac/)| | [لینک](https://www.zoomit.ir/mobile/387227-stellar-galaxy-s23-ultra-hp2-sensor/#2200012) |   در انتظار تأیید
هرزنامه (اسپم):
اگر فردی قصد ارتباط‌ با جناب Amir را دارند، در برنامه‌ی دیسکورد به این سرور بِپِیوَندند:
h t t p s : / / di sc or d.g g/9 2U n U U 4q

«در انتظار تایید...»!

**Comment by Maximilian313** [comment]
پیشتر از دیسکورد استفاده‌هایی داشتم؛ حقیقتاً برنامه‌ی مملو از امکانات و تهی از نقص های ازار دهنده است!
بنیان گذار؟! ایـن دراز گـوش؟!

**Comment by darksilentcore** [comment]
# ایـن دراز گـوش؟!
تو از هر انسان با ارزش تری
این چرت و پرتا چیه میگی

# حقیقتاً برنامه‌ی مملو از امکانات و تهی از نقص های ازار دهنده است
دقیقا

راستی کاربر پیسکل ۷ خیلی ناراحت شد
من که براش اختصاصی نوشتم تو هم بهش یک چیز بگو
واقعا بهش بدی کردیم
البته که ما رفتیم ولی نباید تنهاش بزاریم

**Comment by Maximilian313** [comment]
بله چندین و چندین بار پاسخی برای ایشان ارسال کردم اما زومیت بزرگوار...

**Comment by Maximilian313** [comment]
زومیت آنچنان مرا بر سر بحث با جناب یوسف نژاد محدود کرده است که...
